### ISSUE TITLE
Upgrade to ruby 3.3

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_api#173]
- [ ] Add the new ruby version to CircleCI (see draft PR #170)
- [ ] Fix any failing tests or dependency issues caused by ruby upgrade
- [ ] Provision staging box to use the new ruby version (see draft PR https://github.com/pulibrary/princeton_ansible/pull/4560)
- [ ] Deploy code that works with the new ruby version to staging
- [ ] Manually test on staging box with the new ruby version
- [ ] Provision new boxes or use [this process to upgrade and deploy in place](https://docs.google.com/document/d/1qedt3nKl9nlSmYepT5DPYVcfDB9xvE81Qllmw_cYvf0/edit)
- [ ] Update this issue template with anything we need to keep in mind for the next upgrade

### Implementation notes

We tried this in early January 2024.  It worked locally, but passenger errored on each request with the following error:

```
App 198329 output: /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:259:in `find_spec_for_exe'
App 198329 output: :
App 198329 output: can't find gem bundler (= 2.5.4) with executable bundle (Gem::GemNotFoundException)
App 198329 output:
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:239:in `bin_path'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/rubygems_integration.rb:151:in `bin_path'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/shared_helpers.rb:321:in `bundle_bin_path'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/shared_helpers.rb:307:in `set_bundle_variables'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:20:in `setup'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler.rb:162:in `setup'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/setup.rb:26:in `block in <top (required)>'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/ui/shell.rb:159:in `with_level'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/ui/shell.rb:111:in `silence'
App 198329 output:      from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/setup.rb:26:in `<top (required)>'
App 198329 output:      from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
App 198329 output:      from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
[ E 2024-01-08 20:56:05.4028 198307/Tf age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/allsearch_api/current: The application process exited prematurely.
  Error ID: a675364f
  Error details saved to: /tmp/passenger-error-ZlMU43.html
```

[Passenger hasn't yet released a version that explicitly supports Ruby 3.3 ](https://github.com/phusion/passenger/releases)at this time, we should wait until after they do to see if that fixes the issue.

**Comment by rladdusaw** [comment]
Already completed in #170
